import type { Metadata } from "next";
import { Playfair_Display } from "next/font/google";
import { GeistSans } from "geist/font";
import "./globals.css";

import { Navbar } from "@/components/navbar";

const playfairDisplay = Playfair_Display({
  subsets: ["latin"],
  variable: "--font-playfair",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${GeistSans.className} ${playfairDisplay.variable} max-w-screen-lg mx-auto px-6 xl:px-0`}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
